---
title: Carol Cupas
baseurl: "/"
url: https://www.carolcupas.com
permalink: "/:title/"
palette: green
description: Carol Cupas - Pensamientos, reflexiones y vivencias.
image: "images/CC Website.png"
header:
  title: Carol Cupas
  tagline: Every journey begins with a single step
  logo_img: "/images/logov2b.png"

  bg_img: "/images/CC arte.jpg"
  has_nav: true
  has_social: true
footer:
  #content: "&copy; Todos los derechos reservados."
  links: []
sass:
  indentWidth: 4
  style: nested
  precision: 10

reCAPTCHA_key: 6LdA-L0ZAAAAAJI_x0inm8igBL17L66xyYsbF3v-

plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: posts/:title/
