---
title: Carol Cupas
baseurl: "/"
url: https://www.carolcupas.com
permalink: "/:title/"
palette: green
description: Blog acerca de mis pensamientos y vivencias personales y profesionales.
header:
  title: Carol Cupas
  tagline: Every journey begins with a single step
  logo_img: "/images/logov2b.png"
  image: "/images/CC Website.png"
  bg_img: "/images/CC arte.jpg"
  has_nav: true
  has_social: true
footer:
  content: "&copy; Todos los derechos reservados."
  links: []
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: posts/:title/
